Milestone 1: Portfolio, setup and mobile first.
Jrmcuervo/replica-my-portfolio pull request #1
Opened 2023-01-13 21:08 UTC by Jrmcuervo

### Build header and headline section of template 1.

In this milestone I:
  - Set up a new repository and prepare it for development.
  - Add a professional Readme file.
  - Add gitignore file.
  - Set up linters.
  - Add an html, css, and js file.
  - Build the first 2 sections of the mobile website using template 1 from 
     Figma.

2023-01-13 23:12 UTC, NahnahAJ requested changes
Hi @Jrmcuervo, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/wA6aYAO3jH6RmUIBYs/giphy.gif"/>

## Highlights
- Descriptive PR title and summary :100: 
- Meaningful commit messages :100: 
- Linters are well setup and passing :100: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- Beginning your commit messages with a capital letter to make them more professional. 
eg.  **Added the header section to the page.**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 23:12 UTC, nahnahdev commented on README.md
> +</div>
- [ ] Good job making it this far in your project :muscle: There are just a few things that need to be addressed :wink:
- [ ] Please note that this code block is of no relevance in your README file. Please remove it or replace the template logo with your own logo if you have one. :wink:

2023-01-13 23:12 UTC, nahnahdev commented on README.md
> + -->
- [ ] Kindly remove pieces of comments in your README file to make your repository more professional. :+1:

2023-01-13 23:12 UTC, nahnahdev commented on README.md
> +- [📝 License](#license)
- Every section of the readme template is required with the exception of the FAQ section which is optional. So please make sure to add the missing sections to your project and fill in all the necessary contents :+1:

- [ ] Follow the steps I have listed below to complete the missing or incomplete sections.

    • For the Key Features section, kindly highlight what this project is all about. This will make it easy for those who go through this repository to know what was implemented by reading the README.md file. :wink: 

    • For the Prerequisite Section, kindly add tools that are needed before you can clone this repository on a local machine. Tools like:
        ◦ Installation of Git
        ◦ Installation of NPM
        ◦ A working browser
        ◦ Internet connection
        ◦ A code editor like Visual Studio Code
        ◦ Installation of Live Server plugging in Visual Studio Code
        ◦ Any other tool you can think about :100: 

    • For the Setup section, kindly add instructions for cloning your repository on a local machine :+1: 

    • For the Install section, kindly add instructions for setting up linters used in this project :+1: 

    • For the Usage section, include instructions for opening this project on a browser. For example, opening the project by launching the Live Server plugging in visual studio code or any other means that you know.

- For the Future Features section include 2 or more future features.

2023-01-13 23:12 UTC, nahnahdev commented on idex.html
> +    </nav>
- [ ] Please wrap the (`nav` tag) in a (`header` tag) for semantic reasons and also because typically the (`header` tag) is used as a page header, it contains the site's title or logo (or both) and the main site navigation. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info :wink: 
- [ ] Please wrap your logo in an (`a` tag). This is not only for semantic reasons but to also improve user interactivity. The `href` attribute of the (`a` tag) should be used to add a link to the homepage which takes a user back to the home page when the logo clicked on :100: 
- [ ] Lastly, the font weight of the Figma design looks bolder than yours. Please refer to the images below and fix this as well :100: 
- Your Design
![image](https://user-images.githubusercontent.com/102699958/212432600-8cab88bf-6db7-41a0-9c17-615de97b157f.png)
- The Figma Design
![image](https://user-images.githubusercontent.com/102699958/212432638-b6dadcf0-839c-48df-923d-84be30856fbf.png)

2023-01-13 23:12 UTC, nahnahdev commented on idex.html
> +    </header>
- [ ] This section is supposed to be wrapped in (`section` tags) and not (`header` tags) so please change that as well :wink: The (`section` tags) represent a generic standalone section of the document, so please use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info :100: 
- [ ] Please align the contents of this section using flexbox. Flexbox is used because of its support for responsive design, as elements can automatically adjust their size and position based on the size of the container or viewport :+1: 
- [ ] The social media icons are not showing on the page. The image links might be broken. Please fix this as well. Alternatively, you can use [Font Awesome](https://fontawesome.com/) which gives you access to a wide range of icons that you can use in your project :100: 
- [ ] Please remove the name of the icons so your page can look like the Figma design. Please try to stick to the design as much as possible :+1: 
- Your Design 
![image](https://user-images.githubusercontent.com/102699958/212434035-bbc5a9c1-c3e0-43b7-b9d6-b2363a969fa5.png)
- The Figma Design
![image](https://user-images.githubusercontent.com/102699958/212434574-52d0dc6a-0d24-4e60-8d88-b46391b48209.png)

2023-01-14 01:31 UTC, Ibizugbe approved these changes
Hi @Jrmcuervo 👋, 

![BigTvGIF (3)](https://user-images.githubusercontent.com/64643995/212444445-0562ff4d-b1c6-44e3-ac75-3fe40acb1b9f.gif)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅
- linters are passing👍
- The right github flow method has been used👍

## Optional suggestions
- I think we can make our commit messages more professional by capitalizing every statement🤗 I suggest you take this into consideration in your future projects🤗
_kindly see the comments below for other suggestions_

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 01:31 UTC, Ibizugbe commented on README.md
> +I would like to thank...
[OPTIONAL] I think leaving incomplete statements on your readme makes it look less professional😉 I suggest you complete these incomplete statements. 🤗

2023-01-14 01:31 UTC, Ibizugbe commented on README.md
> +If you like this project...
[OPTIONAL] I think leaving incomplete statements on your readme makes it look less professional😉 I suggest you complete these incomplete statements. 🤗

2023-01-14 04:59 UTC, merged